СourseWorkSite/СourseWorkSite/Controllers/Admin/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using СourseWorkSite.Models;

namespace СourseWorkSite.Controllers
{
    public partial class AdminController : Controller
    {
        DBSiteContext db = new DBSiteContext();
        Admin admin;
        bool globalLoginFailed = false;

        public ActionResult AdminPanel()
        {
            admin = db.Admins.Find(0);//Извлекаем админа из БД
            if (admin.AdminStatus == 1)
            {
                admin.AdminStatus = 0;
                db.Entry(admin).State = EntityState.Modified;
                db.SaveChanges();
                return View("AdminPanel");
            }
            else
                return RedirectToAction("GainAccess");
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [HttpGet]
       public ActionResult GainAccess()
        {
            if (globalLoginFailed)
            {
                ViewBag.Fail = "ОШИБКА ДОСТУПА!!! ВВЕДИТЕ ДЕЙСТВУЮЩИЙ ЛОГИН И ПАРОЛЬ!!!";
                globalLoginFailed = false;
            }
            else
            { ViewBag.Fail = ""; }

            return View();
        }

        [HttpPost]
        public ActionResult GainAccess(string login, string password)
        {
            admin = db.Admins.Find(0);//Извлекаем админа из БД
            if ((login == admin.AdminName) && (password == admin.AdminPassword))
            {
                admin.AdminStatus = 1;
                db.Entry(admin).State = EntityState.Modified;
                db.SaveChanges();
                return AdminPanel();
            }
            else
            {
                globalLoginFailed = true;
                return GainAccess();
            }
        }

    }
}

СourseWorkSite/СourseWorkSite/Controllers/GraphController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using СourseWorkSite.Models;

namespace СourseWorkSite.Controllers
{
    public class GraphController : Controller
    {
        // GET: Graph

        DBSiteContext db = new DBSiteContext();

        public ActionResult GraphOut()
        {
            //Данные для диаграммы с количеством объектов на сайте
            ViewData["CountPlugins"] = db.Plugins.Count();
            ViewData["CountLibrarySamples"] = db.LibrarySamples.Count();
            ViewData["CountDAW"] = db.DAWs.Count();

            List<Producer> listAllProducer = db.Producers.Include(p => p.Plugins).Include(d => d.DAWs).Include(ls => ls.LibrarySamples).ToList();

            for (int i = 0; i < listAllProducer.Count; i++)
            {
                for (int j = 0; j < listAllProducer.Count; j++)
                {
                    if ((listAllProducer[i].Plugins.Count + listAllProducer[i].DAWs.Count + listAllProducer[i].LibrarySamples.Count) >
                        (listAllProducer[j].Plugins.Count + listAllProducer[j].DAWs.Count + listAllProducer[j].LibrarySamples.Count))
                    {
                        Producer prod = listAllProducer[j];
                        listAllProducer[j] = listAllProducer[i];
                        listAllProducer[i] = prod;
                    }
                }
            }

            for (int i = 0; i < 5; i++)
            {
                if (i != 4)
                {
                    ViewData["NameProducer" + (i + 1)] = listAllProducer[0].ProducerName;
                    ViewData["CountObjectProducer" + (i + 1)] = listAllProducer[0].Plugins.Count
                        + listAllProducer[0].DAWs.Count + listAllProducer[0].LibrarySamples.Count;
                    listAllProducer.RemoveAt(0);
                }
                else
                {
                    int countObject = 0;
                    foreach(Producer prod in listAllProducer)
                    {
                        countObject += prod.Plugins.Count
                        + prod.DAWs.Count + prod.LibrarySamples.Count;
                    }
                    ViewData["CountObjectProducerOther"] = countObject;
                }
            }

            List<TypePlugin> listTypePlugins = db.TypePlugins.Include(p => p.Plugins).ToList();
            listTypePlugins.RemoveAt(0);

            for (int i = 0; i < listTypePlugins.Count; i++)
            {
                ViewData["NameTypePlugin" + (i + 1)] = listTypePlugins[i].Type;
                ViewData["CountPlugin" + (i + 1)] = listTypePlugins[i].Plugins.Count;
            }

            return View();
        }


    }
}

СourseWorkSite/СourseWorkSite/Controllers/Main/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using СourseWorkSite.Models;

namespace СourseWorkSite.Controllers
{
    public partial class MainController : Controller
    {

        int globalPageSize = 10;//Переменная с количеством объектов на странице

        DBSiteContext db = new DBSiteContext();
        // GET: Main

        //Главная страница
        public ActionResult HomePage()
        {
            return View();
        }
        
    }
}

СourseWorkSite/СourseWorkSite/Controllers/SkyLineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using СourseWorkSite.Models;

namespace СourseWorkSite.Controllers
{
    public class SkyLineController : Controller
    {
        DBSiteContext db = new DBSiteContext();
        // GET: SkyLine
        public ActionResult Index()
        {
            string src = UrlHelper.GenerateContentUrl("~/Picture/sink.jpg", this.HttpContext);
            ViewBag.Picture = src;
            return View();
        }
    }
}

СourseWorkSite/СourseWorkSite/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Выйти за панели админа", "HomePage", "Main", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Плагины", "TablePlugin", "Admin")</li>
                    <li>@Html.ActionLink("DAW", "TableDAW", "Admin")</li>
                    <li>@Html.ActionLink("Семплы", "TableLibrarySample", "Admin")</li>
                    <li>@Html.ActionLink("Производители", "TableProducer", "Admin")</li>
                    <li>@Html.ActionLink("Типы плагинов", "TableTypePlugin", "Admin")</li>
                    <li>@Html.ActionLink("Пакеты плагинов", "TablePackagePlugin", "Admin")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year by @Html.ActionLink("Mr. SkyLine", "Index", "SkyLine", new { area = "" }, new { @style = "color: black" })</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

СourseWorkSite/СourseWorkSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Имя приложения", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                    <li>@Html.ActionLink("О программе", "About", "Home")</li>
                    <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

СourseWorkSite/СourseWorkSite/Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <right>
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Главная", "HomePage", "Main", new { area = "" }, new { @class = "navbar-brand" })
                </right>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Плагины", "PagePlugin", "Main")</li>
                    <li>@Html.ActionLink("DAW", "PageDAW", "Main")</li>
                    <li>@Html.ActionLink("Семплы", "PageLibrarySample", "Main")</li>
                    <li>@Html.ActionLink("Производители", "PageProducer", "Main")</li>
                    <li>@Html.ActionLink("Пакеты плагинов", "PagePackagePlugin", "Main")</li>
                    <li>@Html.ActionLink("Информация в виде диаграмм", "GraphOut", "Graph")</li>
                    <li>|<br>|</li>
                    <li>|<br>|</li>
                    <li>|<br>|</li>
                    <li>@Html.ActionLink("Войти как администратор", "AdminPanel", "Admin")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year by @Html.ActionLink("Mr. SkyLine", "Index", "SkyLine", new { area = "" }, new {@style = "color: black" })</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>